name: pocketbase_auth_anonymously
description: "Lightweight extension for the `pocketbase` Dart client that creates and signs-in an anonymous user."
version: 0.0.1
homepage: https://github.com/lamnhan066/pocketbase_auth_anonymously

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  pocketbase: ^0.24.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.16.0
